const asyncHandler = require("express-async-handler")
require("dotenv").config()
const { connectDB } = require("../config/db")
const User = require("../model/user.model")
const Pass = require("../model/pass.model")
const { ErrorHandler } = require("../middleware/errorMiddleware")

//@desc Generate a pass by user
//@route POST /users/generatePass
const generatePass = asyncHandler(async (req, res, next) => {
  try {
    await connectDB()
    const { name, email, phone, duration, start } = req.body

    const user = await User.findOne({ _id: req.user._id })
    if (user) {
      // console.log(user);
      const newPass = await Pass.create({
        name,
        phone,
        email,
        duration,
        start,
        checkInStatus: false,
        generateId: user.id,
        userName: req.user.name,
      })
      if (newPass) {
        res.status(201).json({
          success: true,
          newPass: newPass,
          message: "Pass generated successfully",
        })
      }
    } else {
      throw new ErrorHandler(401, "Signup to create Pass!")
    }
  } catch (err) {
    next(err)
  }
})

//@desc View all passes generated by a user
//@route Get /users/viewPasses
const viewPasses = asyncHandler(async (req, res, next) => {
  try {
    await connectDB()
    const user = await User.findById(req.user._id)
    // console.log(user.id)

    const passes = await Pass.find({ generateId: user.id })

    // console.log(passes)
    if (passes.length > 0) {
      res.status(201).json({
        success: true,
        passes: passes,
        message: "Passes fetched successfully",
      })
    } else if (passes.length < 1) {
      throw new ErrorHandler(404, "No passes found")
    }
  } catch (err) {
    next(err)
  }
})

//@desc Verify pass by gaurd
//@route PUT /users/verifyPass
const verifyPass = asyncHandler(async (req, res, next) => {
  try {
    await connectDB()
    const user = await User.findById(req.user._id)
    console.log(req.params._id)

    const passVerified = await Pass.findOneAndUpdate(
      { _id: req.params._id },
      {
        checkInStatus: true,
        timeAtCheckIn: new Date(),
      }
    )
    // console.log(passVerified)
      res.status(201).json({
        success: true,
        passVerified: passVerified,
        message: "Pass verified successfully",
      })
  } catch (err) {
    next(err)
  }
})

module.exports = { generatePass, viewPasses, verifyPass }
